services:
    openssh-server:
        image: registry.cn-shenzhen.aliyuncs.com/public-l7bug-dev/my-sshd:20251102
#        image: lscr.io/linuxserver/openssh-server:latest
        container_name: openssh-server
        restart: unless-stopped
#        environment:
#            - PASSWORD_ACCESS=true
#            - USER_PASSWORD=123456
#            - USER_NAME=openssh-dev
#        ports:
#            - "22"  # 将主机的2222端口映射到容器的22端口(SSH)
#        volumes:
#            - ./.config-data:/config  # 持久化存储SSH配置
        networks:
            existing_network:
                ipv4_address: 172.29.0.22

networks:
    existing_network:
        external: true
        name: dev-network  # 替换为您的已存在网络名称