version: '3.8'
services:
    java21:
        image: eclipse-temurin:21
        networks:
            - dev-network
        environment:
            TZ: Asia/Shanghai

networks:
    dev-network: # 隔离网络提升安全性
        external: true  # 关键：声明此网络已在外部创建
